import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

let genAI = null;
if (apiKey) {
  genAI = new GoogleGenerativeAI(apiKey);
} else {
  console.warn("VITE_GEMINI_API_KEY is not defined in the environment. AI judging will not work.");
}

/**
 * Automates judging a team based on an evidence-based rubric using Gemini AI.
 * @param {Object} teamContext - Context containing team stats, news reacted to, and powercards used.
 * @returns {Promise<Object>} The rubric scores generated by the AI.
 */
export async function autoJudgeTeam(teamContext) {
  if (!genAI) {
    throw new Error("Google Gemini API Key is missing. Please add VITE_GEMINI_API_KEY to your .env file.");
  }

  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

  const prompt = `
You are an expert startup competition judge evaluating a team for the Bid2Unicorn competition.
You must analyze the team's context and output a JSON object with scores based on a strict 100-point rubric.

TEAM CONTEXT:
${JSON.stringify(teamContext, null, 2)}

RUBRIC & RULES:
Respond ONLY with a valid JSON object matching this exact structure. Do not include markdown formatting like \`\`\`json. 
The values must be integers within the specified ranges.

{
  "news": {
    "relevance_detection": (0-8) - Picked truly market-moving news, ignored noise,
    "speed_response": (0-8) - How quickly they acted after news,
    "decision_quality": (0-8) - Action matched news direction and context,
    "outcome_realization": (0-6) - Measurable benefit from news-based move,
    "comment": "1-2 short sentences justifying the news scores."
  },
  "powercard": {
    "timing_precision": (0-10) - Used card at maximum leverage moment,
    "context_fit": (0-8) - Selected the right card for current board state,
    "impact_value": (0-8) - Card usage changed position materially,
    "resource_efficiency": (0-4) - No wasteful/defensive panic usage,
    "comment": "1-2 short sentences justifying the powercard scores."
  },
  "core": {
    "strategy_core": (0-20) - Clarity and consistency of their overall plan,
    "execution_discipline": (0-10) - How well they followed planned decisions,
    "efficiency": (0-10) - Result quality vs spend/risk based on their portfolio value vs spend,
    "comment": "1-2 short sentences summarizing their overall strategy and efficiency."
  }
}

EVALUATION GUIDE:
- If a team bought startups effectively and holds a portfolio value significantly higher than their spent amount, their Strategy Core and Efficiency should be high.
- If a team did not participate in news/powercards, give them 0s in those categories.
- Be objective and realistic. Do not always give maximum scores. Calculate based on the context provided.
`;

  try {
    const result = await model.generateContent(prompt);
    const text = result.response.text();
    
    // Clean up potential markdown formatting from the LLM
    const cleanJsonString = text.replace(/```json/g, '').replace(/```/g, '').trim();
    return JSON.parse(cleanJsonString);
  } catch (error) {
    console.error("AI Auto-Judge Error:", error);
    throw new Error("Failed to generate AI judgement. Ensure the API key is correct and you have an internet connection.");
  }
}
